export const colors = {
    background: '#0e0e0e',
    surface: '#0e0e0e',
    surfaceContainer: '#1a1a1a',
    surfaceContainerHigh: '#20201f',
    surfaceContainerHighest: '#262626',
    surfaceBright: '#2c2c2c',
    surfaceVariant: '#262626',
    primary: '#f4ffc9',
    primaryDim: '#c1ed00',
    primaryContainer: '#cefc22',
    onPrimaryContainer: '#4b5e00',
    secondary: '#ff734a',
    tertiary: '#81ecff',
    tertiaryContainer: '#00e3fd',
    onSurface: '#ffffff',
    onSurfaceVariant: '#adaaaa',
    outlineVariant: '#484847',
} as const;